[package]
name = "HoshiKitsune"
version = "0.1.0"
edition = "2024"

[dependencies]
inkwell = { version = "0.6.0", features = ["llvm18-1"] }
nom = "8.0.0"
nom_locate = "5.0.0"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
